import { Quiz } from '../lib/supabase'; // Import Quiz type from supabase.ts

interface QuizDisplayProps {
  quiz: Quiz;
}

export function QuizDisplay({ quiz }: QuizDisplayProps) {
  if (!quiz || !quiz.questions || quiz.questions.length === 0) {
    return <div className="text-center text-gray-600">No quiz data to display.</div>;
  }

  return (
    <div className="space-y-8">
      <h2 className="text-3xl font-bold text-gray-900 text-center drop-shadow-sm">
        {quiz.topic} Quiz ({quiz.difficulty})
      </h2>
      <p className="text-center text-gray-700">Generated by {quiz.ai_model_used || 'AI'} on {new Date(quiz.created_at).toLocaleDateString()}</p>

      {quiz.questions.map((question, qIndex) => (
        <div key={question.id || qIndex} className="bg-blue-50/80 backdrop-blur-sm rounded-xl shadow-md p-6 border border-blue-200">
          <p className="text-xl font-semibold text-gray-900 mb-4 text-center">
            Question {qIndex + 1}: {question.question}
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            {question.options.map((option, cIndex) => (
              <div
                key={cIndex}
                className={`p-3 rounded-lg border text-center ${
                  cIndex === question.answer_index
                    ? 'bg-green-100 border-green-300 text-green-800 font-medium'
                    : 'bg-white border-gray-300 text-gray-800'
                }`}
              >
                {option}
              </div>
            ))}
          </div>
          <div className="text-sm text-gray-700 mt-4 space-y-2">
            {question.source_reference && <p><strong>Source Reference:</strong> {question.source_reference}</p>}
            <p><strong>Explanation:</strong> {question.explanation}</p>
          </div>
        </div>
      ))}
    </div>
  );
}